# Generated by Django 4.0.6 on 2022-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
