# Generated by Django 4.0.6 on 2022-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, help_text='with +cc-number', max_length=15, null=True),
        ),
    ]
